apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notification-utils
  description: Notification Utils
  labels:
    license: MIT
spec:
  type: website
  lifecycle: experimental
  owner: cds-snc
