name: 'Waffles'
description: 'Verifies reachability of Flask self-discovered endpoints against AWS WAF environment.'
author: 'CDS cooks'
inputs:
  app-libs:
    description: "Project's libs directory location."
    required: true
  app-loc:
    description: "Project's directory location."
    required: true
  flask-mod:
    description: "Flask app module to execute."
    required: true
  flask-prop:
    description: "Flask app property in the module."
    required: true
  base-url:
    description: "Base URL used to hit the application with discovered Flask endpoints."
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app-libs }}
    - ${{ inputs.app-loc }}
    - ${{ inputs.flask-mod }}
    - ${{ inputs.flask-prop }}
    - ${{ inputs.base-url }}
branding:
  icon: 'target'  
  color: 'yellow'